default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: september_development
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: september_test
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: september_production
  username: september
  password: <%= ENV["SEPTEMBER_DATABASE_PASSWORD"] %>
